name: midday-dashboard
services:
  - name: dashboard
    git:
      branch: main
      repo_clone_url: ${GITHUB_REPO_URL}
    build_command: |
      npm install --production --legacy-peer-deps
      npm run build
    run_command: npm start
    source_dir: deploy
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
    instance_count: 1
    instance_size_slug: basic-xxs
